
namespace DescentDirX.Helpers
{
    enum ImageListEnum
    {
        // COMMON
        LOGO_DESCENT,

        // MAPS
        TILES_9_A,
        TILES_EDGE_A,
        TILES_ENTER_A,
        TILES_EXIT_A,
        TILES_12_A,
        TILES_16_A,
        TILES_8_A,
        TILES_26_A,

        // HEROES
        HEROES_SYNDRAEL,
        HEROES_SYNDRAEL_PORTRAIT,
        HEROES_SYNDRAEL_SHEET,
        HEROES_SYNDRAEL_TOKEN,

        HEROES_LEORIC,
        HEROES_LEORIC_PORTRAIT,
        HEROES_LEORIC_SHEET,
        HEROES_LEORIC_TOKEN,

        CLASSES_KNIGHT,
        CLASSES_KNIGHT_WOODEN_SHIELD,
        CLASSES_KNIGHT_IRON_LONGSWORD,
        CLASSES_KNIGHT_OATH_OF_HONOR,

        CLASSES_RUNEMASTER,
        CLASSES_RUNEMASTER_ARCANE_BOLT,
        CLASSES_RUNEMASTER_RUNIC_KNOWLEDGE,

        // MONSTERS
        MONSTERS_ETTIN_1_BACK,
        MONSTERS_ETTIN_1_FRONT,
        MONSTERS_ETTIN_1_PORTRAIT,
        MONSTERS_ETTIN_TOKEN,
        MONSTERS_ETTIN_MASTER_TOKEN,
        MONSTERS_GOBLIN_ARCHER_1_BACK,
        MONSTERS_GOBLIN_ARCHER_1_FRONT,
        MONSTERS_GOBLIN_ARCHER_1_PORTRAIT,
        MONSTERS_GOBLIN_TOKEN,
        MONSTERS_GOBLIN_MASTER_TOKEN,

        // TOKENS
        TOKENS_DISEASE,
        TOKENS_IMMOBILE,
        TOKENS_POISON,
        TOKENS_SEARCH,
        TOKENS_STUN,

        // ICONS
        TOKENS_MOVE_ICON,
        TOKENS_FATIGUE_ICON,
        TOKENS_DAMAGE_ICON,
        TOKENS_DEFENSE_ICON,

        // DICES
        DICES_BLACK_ICON,
        DICES_BLACK_SIDE_0,
        DICES_BLACK_SIDE_1,
        DICES_BLACK_SIDE_2,
        DICES_BLACK_SIDE_3,
        DICES_RED_ICON,
        DICES_RED_SIDE_0,
        DICES_RED_SIDE_1,
        DICES_RED_SIDE_2,
        DICES_RED_SIDE_3,
        DICES_YELLOW_ICON,
        DICES_YELLOW_SIDE_0,
        DICES_YELLOW_SIDE_1,
        DICES_YELLOW_SIDE_2,
        DICES_YELLOW_SIDE_3,
        DICES_YELLOW_SIDE_4,
        DICES_YELLOW_SIDE_5,
        DICES_BLUE_ICON,
        DICES_BLUE_SIDE_0,
        DICES_BLUE_SIDE_1,
        DICES_BLUE_SIDE_2,
        DICES_BLUE_SIDE_3,
        DICES_BLUE_SIDE_4,
        DICES_BLUE_SIDE_5,
        DICES_BROWN_ICON,
        DICES_BROWN_SIDE_0,
        DICES_BROWN_SIDE_1,
        DICES_BROWN_SIDE_2,
        DICES_GREY_ICON,
        DICES_GREY_SIDE_0,
        DICES_GREY_SIDE_1,
        DICES_GREY_SIDE_2,
        DICES_GREY_SIDE_3,
    }
}

